apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-micro
  template:
    metadata:
      labels:
        app: a-micro
    spec:
      containers:
        - name: a-micro
          image: mytrgor/a-micro:latest
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
