apiVersion: v1
kind: Service
metadata:
  name: b-micro-service
spec:
  selector:
    app: b-micro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-micro-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b-micro
  template:
    metadata:
      labels:
        app: b-micro
    spec:
      containers:
        - name: b-micro-container
          image: mytrgor/b-micro:v1.0.5
          ports:
            - containerPort: 8081
